export const SET_EMAIL_SUBSCRIPTION_PENDING = 'SET_EMAIL_SUBSCRIPTION_PENDING';
export const SET_EMAIL_SUBSCRIPTION_FULFILLED = 'SET_EMAIL_SUBSCRIPTION_FULFILLED';
export const SET_EMAIL_SUBSCRIPTION_REJECTED = 'SET_EMAIL_SUBSCRIPTION_REJECTED';
